name: Build Obfuscate BPB Panel

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"  
          cache: npm  

      - name: Install dependencies
        run: npm install javascript-obfuscator@latest --save-dev  

      - name: Download source
        run: |
          if ! curl -sfL -o origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js; then
            echo "::error::Failed to download source file"
            exit 1
          fi

      - name: Obfuscate code
        run: npx javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --control-flow-flattening true \
          --control-flow-flattening-threshold 0.75 \ 
          --dead-code-injection true \
          --dead-code-injection-threshold 0.4 \  
          --identifier-names-generator hexadecimal \
          --rename-globals true \
          --string-array true \
          --string-array-encoding rc4 \
          --string-array-threshold 0.75 \
          --transform-object-keys true \
          --unicode-escape-sequence true

      - name: Commit changes
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":arrow_up: update latest bpb panel [skip ci]"  
          commit_author_name: "GitHub Actions"
          commit_author_email: "41898282+github-actions[bot]@users.noreply.github.com"
          file_pattern: "_worker.js" 
